---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.2/manifests/install.yaml

configMapGenerator:
- name: argocd-cm
  behavior: merge
  literals:
  - kustomize.buildOptions=--enable-helm
