---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets

helmCharts:
  - name: sealed-secrets
    version: 2.14.1
    releaseName: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
