---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

helmCharts:
  - name: traefik
    version: 26.0.0
    repo: https://traefik.github.io/charts
    valuesInline:
      providers:
        kubernetesCRD: enabled
