---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

helmCharts:
  - name: prometheus-community
    version: 55.5.0
    releaseName: prometheus-community
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
