---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

helmCharts:
  - name: kube-prometheus-stack
    version: 55.1.0
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
