---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-system

helmCharts:
  - name: ingress-nginx
    version: 4.9.0
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    valuesInline:
      controller:
        service:
          loadBalancerIP: 192.168.2.200
