---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-system

helmCharts:
  - name: ingress-nginx
    version: 4.8.4
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    includeCRDs: true
