---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: "*.192.168.2.200.nip.io"
  tls:
    - hosts:
        - "*.192.168.2.200.nip.io"
      secretName: tls
