---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-ingress
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  ingressClassName: nginx
  rules:
    - host: "*.lab.azizified.com"
  tls:
    - hosts:
        - "*.lab.azizified.com"
      secretName: tls
