---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmCharts:
  - name: cert-manager
    version: 1.13.3
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    valuesInline:
      global:
        leaderElection:
          namespace: cert-manager
        webhook:
          securePort: 10251
          hostNetwork: true
      installCRDs: true
      namespace: cert-manager
