---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgAt3AQTkbU687CdQMX/ArZ89uA/8PEXYOrlxVQhcpJdMkFPFDRmDQMkOJBOQmN3SktJ/t9nWJDQreF4vmBNiWqYCNvHPze/F4YdTlUHDbPtS8ncSy+fypHtAzPD/FxseWXfaKrFZ0kHjkFuHklrH/dcRA+dq7vcbj2q7/DE8SKwZT0fUHIvTh0Z3Dp41J9vJjfhcJ4fys57uKokB+7nQGNfcCZ5g4e2QKPPGkJZjsGVhMfB4VsQ5IMG5URA7Zhs3Hl0PFcc+ei9hbuaYIHx+fpPw/8GskB4EYtfAv/8jh3GnOnZeWsJcJeDi6okmu3EionDAFIJ3se1kh6oK+rh7vRIzhgaP5YSvbeaOaiEdZQlpLGdQbiuSjD05p4BFPdAsg5R1v6PNjeOXQ0A8rmBREr0IN9W2PULbnIBaTkAuiNzcnOmyekdWhHnQ7fp7LtTYTUb/ASMjaRQ+pT8Ke2aH39OK4p/lwd8Y8bMeKMTphfWfWNVMbcOWXHVCQxRcHDeaW5btBsUfMi8XrgzR1yrJMrf+GnrA5hvH7QxJ8jMJC82/mJpKt2RcxYnyeBsnTmEB9nAq9yY0nsDnLm1TnkrnyZ1cbllZXK6UAFFr15x3bR746jz270grTA4MpVbQfRoGsWjhAKjfOL/A0J+/M9T9THRo3vGRy0KNs5GGe1RRAKtZ2iVPNkAlSzwziZFMsXudTozC1e+W59D0NufUC6qyE+fA7BnSFacUBinSri2Zg4jrKLHeQrSdA/mAw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
