---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgAq8Z5pL2+gbYQWU7liinhqWVlmApducU1Yy8ju0WOsJIIenK+9oDOR0zlnKrdDsiDfpI5PAAwoFtZJ48UTrwiSv2VZ4PkUd/Fk1MwWKmB1IGQc5rpXYjLqm8PdcmIcnk5PJRGbYNj16FNw5A7rnyLRFJoxkB1YQZJxHgWuKn7ufgj8QnzRB/Clp0pVji+50Z33Byeeu+0+Dqm2dYPeMkNHxiaH9pIBrPsMLjWvoLJ7OPZO5AUw8cHDvtiqbTiRsXjpNXb46nENJkwLAJKnR+i7NcidzUfKj/OW0LrnpdwtiK4QxpcQQ/zBsnzqc47k+ICqMCbmq2gqgsFwLPa0FXgwihRV0WfXoYUUxrJoMXhcrA+B8pcWj/uOYJN77fJ4FOqaqYlL7uvq7+n5EcMTIOKwuSCoMyK4npXkpDIxAKM5i9MvShdUNnP+Ct+jGSOAJvTtwA1MrnLYhkSbEWspoOwA8H5eNgaSeGrQz5eeE+g55XV0Hg9SyI6sNNGDSs+jhKpGaoy+LorrSqvyPj4Bv5Mzh0q/pJ+hon4E+Np1VI54RO5NPt6PE7igGZnN0Av4wXjcS62qoB6roiM4TraXn3DB0b9irpVUsaodWED+sSTmwdHAF5l8Yn9fUHKr1fizIX0DMAJZnfWe/tabUm/K+bFEH39A7fOkUBtdCAQQUMLAwkTbN8+LTDdOIr3t2IxkX0FrXZ8qJ7KOly3it4LdK7ib9veFIutTUV6gyU9JDmExH16LRFVNdfdV
  template:
    metadata:
      name: cloudflare-api-token-secret
