---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgBg8NcbY0QlaKh8/0meBcCJ3+SS9IUjIxJecTPncwqdQEablvwwQdnIoOUoX7dvN/pvZAIyI5kQbPfi3Lj7QmBRWrQ7908EMlsZGv4fdQOTcqmhrR1qMyq+FM9Gyd1JveovElH/ommAdJVPpOIoV8lddQPR+yZ9xZ+1M1e8bP3gsqc9yZ9W3a/r5kVTo5h6q1L1A1wh8Jw+hcAiGDw/pdCWYx0+ePykwBFcbVDN9kc7cpvae2+IIKQjdA2EHCFpg8d94C8T2YO3+Jy+6EPdMKc4Jg+S/2VIq4yRjn0glXMKkmSShCqYThIucxx7qnDJ/0uCwzco09szZ0+33OVEXC7dPjTSeALwJ+f8Yb5qWxOpjrsjKU5lpmTqgmxso7BOhE8eaXTzT1ikVLMa4DMTkgOU1Dac0H005fA9FcLI/r+ued+I94vosaGBu0hc51ALcR0O7kI30iVvIKKJ6Rdv8hborR4AhbG+MIeWXzNjlpQYScUbaoOyh3Nio8OQq4ZUeAbEvxzKOHLHdKVclvu9utGlPmIq4oKMkvrl7jBIK9Q7557SlGmTtCk0oGLBkyGDXzruNLs94QPFIRxg7FBQfP7XorO3hrZKU6BAYtCSTX7ol2UeDk0evP9JKoIXxnVxDpu2nI4+Gr6u/53bkat8LpcXoBkB9hmCISVJMAduoTfOE6Xji6mWArIIzHAONfnI4Ngyva71l08jdSV+6th1amNASiQHadJSSvmzoU5Dt+c=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
