---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgA0YO1Fj6dWBbyUb7gNflrj40J8hm61KEhAiBKhdVVNDs20FbCwshuEerMvz1bLWEvKpLI70hIZm0my/SYK9CtpYWmNXWJhro/e8kiC21+sUttXgzAmFOqRkpaLn+qkky6zg319caBpz1ds5BZbLFpo8v7w/vW6WNtKBfTNoHVw+LqUJqcny77Xtdropw5KPG/njbrLj8LDLQUeAuBRdY6hRTcdaETzkNOhBlQhITt/iA+C9EjZDnGC/P8d9VHhlL+brlBLVtE82v15YNWLrAChV0EluMjjfjSEYm6PmhUQn4lhaT8W2wt7fiB5oQOp0nYNmHXarf2DaxIiy856ZBg3zEwFMjOUK7VfyDNPVU2BPIsut+mscX+IfuwJMOPSMVnPn1691+vaJiVGKALxqpjmfpzxRtQWOieW/jLNjK4DdLUBw6TLOWiHtSZb9nS8UwIucxXH3kGnFEumODjvvExt6OFmZ9W5a+0+zmIvcSlCmCdOBUsgMjiLpelX5euH4wlXgTdj2fGBBgJ183UM1sRK03EFPUTTwAJiGtWzHg3QQNdeKfeGhNACp/C7IHNC3Q+Owb7CQtctO7ZhsscKCHXxE5jReCxBPr4B2h5uT3iMpk/NtbcjZRRD8UnqrSygfeXPyIHv3nCvJtlP/MkPadk9MaTmN1d4l05Mfb7csBXJtth4vlKY1U5OYLy2WDqDDo+KqzV0QDor2URvelwlUb8TBqEQfCDpo1Hjl1GDYUmvBLLtN+EpMbQh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
